#!/usr/bin/env python3
"""Generate docs/metrics.md from the metric catalog.

python3 tools/gen_metrics_doc.py          # rewrite docs/metrics.md
python3 tools/gen_metrics_doc.py --check  # fail if it is out of date (CI)
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from proxmox_node_exporter.collectors import ALL_COLLECTORS  # noqa: E402
from proxmox_node_exporter.manager import M as EXPORTER_METRICS  # noqa: E402
from proxmox_node_exporter.metrics import CATALOG  # noqa: E402

OUTPUT = ROOT / "docs" / "metrics.md"


def render() -> str:
    lines = [
        "# Metrics reference",
        "",
        "<!-- Generated by tools/gen_metrics_doc.py from the metric declarations; do not edit. -->",
        "",
        "Each collector only runs where it is supported (see `--list-collectors`), so a host",
        "exposes the subset of these metrics that applies to its hardware and software.",
        "",
    ]
    groups = [(cls.name, cls.description) for cls in ALL_COLLECTORS]
    groups.append((EXPORTER_METRICS.group, "Exporter self-monitoring and process metrics"))
    for group, description in groups:
        specs = sorted((s for s in CATALOG.values() if s.group == group), key=lambda s: s.name)
        if not specs:
            continue
        lines += [f"## {group}", "", description + ".", ""]
        lines += ["| Metric | Type | Labels | Description |", "| --- | --- | --- | --- |"]
        for spec in specs:
            labels = ", ".join(f"`{label}`" for label in spec.labels) or "-"
            text = spec.help.replace("|", "\\|")
            lines.append(f"| `{spec.name}` | {spec.type} | {labels} | {text} |")
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="only check, do not write")
    args = parser.parse_args()
    content = render()
    if args.check:
        current = OUTPUT.read_text() if OUTPUT.exists() else ""
        if current != content:
            print(f"{OUTPUT.relative_to(ROOT)} is out of date; run tools/gen_metrics_doc.py")
            return 1
        return 0
    OUTPUT.parent.mkdir(exist_ok=True)
    OUTPUT.write_text(content)
    print(OUTPUT.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    sys.exit(main())
